/*
 * Copyright (c) 2016 Waritnan Sookbuntherng
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package com.lion328.thaifixes;

import java.io.File;
import java.util.Arrays;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.client.event.ConfigChangedEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

@Mod(name = Core.NAME, modid = Core.MODID, version = Core.VERSION, dependencies = Core.FORGE_VERSION, guiFactory = Core.GUI_FACTORY, clientSideOnly = true)
public class Core
{
    protected static final String MODID = "thaifixes";
    protected static final String NAME = "ThaiFixes";
    protected static final String VERSION = "3.0";
    protected static final String FORGE_VERSION = "required-after:Forge@[11.15.1.2318,);";
    protected static final String GUI_FACTORY = "com.lion328.thaifixes.ConfigGuiFactory";
    public static final Logger LOGGER = LogManager.getFormatterLogger("ThaiFixes");

    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        ThaiFixesConfigManager.init(new File(event.getModConfigurationDirectory(), "thaifixes.cfg"));
        MinecraftForge.EVENT_BUS.register(this);

        ModMetadata info = event.getModMetadata();
        info.autogenerated = false;
        info.modId = MODID;
        info.name = NAME;
        info.version = VERSION;
        info.url = "http://thaifixes.lion328.com/";
        info.authorList = Arrays.asList("lion328");
        info.credits = "PCXD, secretdataz";
        info.description = "ช่วยให้การแสดงผลของภาษาไทยออกมาอย่างถูกต้อง";
    }

    @SubscribeEvent
    public void onConfigChanged(ConfigChangedEvent.OnConfigChangedEvent event)
    {
        if (event.modID.equalsIgnoreCase(MODID))
        {
            ThaiFixesConfigManager.syncConfig(false);
        }
    }
}