/*
 * Copyright (c) 2017 Waritnan Sookbuntherng
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package com.lion328.thaifixes;

import java.util.Arrays;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(name = ThaiFixes.NAME, modid = ThaiFixes.MOD_ID, version = ThaiFixes.VERSION, clientSideOnly = true)
public class ThaiFixes
{
    public static final String VERSION = "4.9.0";
    public static final String MOD_ID = "thaifixes";
    public static final String NAME = "ThaiFixes";
    public static Logger LOGGER = LogManager.getLogger("ThaiFixes");

    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        ThaiFixes.init(event.getModMetadata());
    }

    private static void init(ModMetadata info)
    {
        info.autogenerated = false;
        info.modId = ThaiFixes.MOD_ID;
        info.name = ThaiFixes.NAME;
        info.version = ThaiFixes.VERSION;
        info.url = "https://minecraft.lion328.com/thaifixes/";
        info.description = "Improve Thai characters support in Minecraft.";
        info.authorList = Arrays.asList("lion328", "SteveKunG");
        info.credits = "PCXD, secretdataz";
    }
}